CREATE TABLE IF NOT EXISTS areas (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  inscricao VARCHAR(80) NOT NULL UNIQUE,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pastos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  area_id INT UNSIGNED NOT NULL,
  nome VARCHAR(100) NOT NULL,
  capacidade INT UNSIGNED NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pastos_area FOREIGN KEY (area_id) REFERENCES areas(id),
  CONSTRAINT uq_pasto_area UNIQUE (area_id, nome)
);

ALTER TABLE animais ADD COLUMN pasto_id INT UNSIGNED NULL;
ALTER TABLE animais ADD CONSTRAINT fk_animais_pasto FOREIGN KEY (pasto_id) REFERENCES pastos(id) ON DELETE SET NULL;
