CREATE TABLE IF NOT EXISTS eventos_agenda (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(150) NOT NULL,
  descricao VARCHAR(1000) NULL,
  data_evento DATETIME NOT NULL,
  prioridade ENUM('BAIXA','MEDIA','ALTA') NOT NULL DEFAULT 'MEDIA',
  recorrencia ENUM('NENHUMA','DIARIA','SEMANAL','MENSAL','ANUAL') NOT NULL DEFAULT 'NENHUMA',
  antecedencia_minutos INT UNSIGNED NOT NULL DEFAULT 1440,
  status ENUM('PENDENTE','CONCLUIDO') NOT NULL DEFAULT 'PENDENTE',
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_agenda_data_status (status, data_evento)
);
